refactor: show 280-char of page if missing summary
Rather than crashing a build with a cryptic error:

    Error: Failed to render pager 1
    Reason: Failed to render 'zola-pickles/templates/index.html': error while rendering macro `post_macros::polish`
    Reason: Filter `replace` was called on an incorrect value: got `null` but expected a String

when a page is missing a summary, this just shows the first 280-chars
(280 inspired by twitter) of the page as the page summary.

Closes #2.